import { fileURLToPath, URL } from "node:url";
import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./", import.meta.url)),
    },
  },
  test: {
    environment: "node",
    include: [
      "src/lib/__tests__/ai*.test.{ts,tsx}",
      "src/lib/__tests__/aiInsightsRead.test.ts",
      "src/lib/__tests__/aiPendingPlanSurvives.test.ts",
      "src/lib/__tests__/orderItemGroups.test.ts",
      "src/lib/__tests__/billPromotions.test.ts",
      "src/lib/__tests__/homeDashboard.test.ts",
      "src/lib/__tests__/kitchenSort.test.ts",
      "src/lib/__tests__/reportRange.test.ts",
      "src/lib/__tests__/documentTitle.test.ts",
      "src/lib/__tests__/googleOAuth.test.ts",
      "src/lib/__tests__/docsContent.test.ts",
      "src/lib/__tests__/customerOrderView.test.ts",
      "src/lib/__tests__/invitation.test.ts",
      "src/lib/__tests__/noManualRefreshControls.test.ts",
      "src/lib/__tests__/mediaUrl.test.ts",
      "src/lib/__tests__/menuImageCrop.test.ts",
      "src/lib/__tests__/landingPhoneMockup.test.ts",
      "src/lib/__tests__/authModalMotion.test.ts",
      "src/lib/__tests__/brandWordmark.test.ts",
      "src/lib/__tests__/orderNavigation.test.ts",
      "src/lib/__tests__/orderEvents.test.ts",
      "src/lib/__tests__/posTableNavigation.test.ts",
      "src/lib/__tests__/qr.test.ts",
      "src/lib/__tests__/requestGeneration.test.ts",
      "src/lib/__tests__/roleLabels.test.ts",
      "src/lib/__tests__/safeRedirect.test.ts",
      "src/lib/__tests__/restaurantPath.test.ts",
      "src/lib/__tests__/restaurantScopedNavigation.test.ts",
      "src/lib/__tests__/reservationSchedule.test.ts",
      "src/lib/__tests__/reservation.test.ts",
      "src/lib/__tests__/singleFlight.test.ts",
      "src/lib/__tests__/chatComposer.test.ts",
      "src/lib/__tests__/aiPendingPlanStorage.test.ts",
      "src/app/(dashboard)/r/[slug]/orders/ordersPageUtils.test.ts",
      "src/app/(dashboard)/r/[slug]/tables/tablesPageUtils.test.ts",
      "src/app/(dashboard)/r/[slug]/inventory/inventoryPageUtils.test.ts",
      "src/app/(dashboard)/r/[slug]/inventory/inventoryHistoryUtils.test.ts",
      "src/app/(dashboard)/r/[slug]/inventory/inventoryExpiryUtils.test.ts",
      "src/app/(dashboard)/r/[slug]/inventory/inventoryUnitUtils.test.ts",
      "src/app/(dashboard)/r/[slug]/inventory/inventoryFormValidation.test.ts",
      "src/app/(dashboard)/r/[slug]/expenses/expensesPage.test.ts",
      "src/app/(dashboard)/r/[slug]/promotions/promotionRules.test.ts",
      "src/app/(dashboard)/r/[slug]/staff/staffPermissionPolicy.test.ts",
      "src/app/(dashboard)/r/[slug]/settings/_components/SettingsPrimitives.test.tsx",
      "src/hooks/useDialogFocus.test.ts",
      "src/app/(dashboard)/r/[slug]/settings/restaurant/restaurantSettingsForm.test.ts",
      "src/lib/__tests__/serialQueue.test.ts",
      "src/lib/__tests__/branchLabel.test.ts",
      "src/lib/__tests__/reorder.test.ts",
      "src/lib/__tests__/takeawayOrders.test.ts",
      "src/components/shared/RealtimeConnectionNotice.test.tsx",
      "src/components/shared/InlineDbConfirmBar.test.tsx",
      "src/components/shared/AppWordmark.test.tsx",
      "src/components/shared/ThemedSelect.test.tsx",
      "src/components/shared/ThemedMultiSelect.test.tsx",
      "src/components/shared/ThemedTimeInput.test.tsx",
      "src/components/shared/nativePickers.touch.test.tsx",
      "src/components/docs/DocsContent.test.tsx",
    ],
  },
});
